### ISSUE TITLE
problem in angular material design

### ISSUE THREAD

**Issue by manvfx** [Ni55aN/D3NE-examples#4]
I have a problem in Angular Material Design. Unfortunately, when the component is implemented, it will display a problem.

please help me

![123](https://user-images.githubusercontent.com/6747872/38085124-b0266592-3364-11e8-8efb-7f7592579030.jpg)

**Comment by Ni55aN** [comment]
Have you tried to luanch [an example](https://github.com/Ni55aN/D3NE-examples/tree/master/Angular)? What version of Angulare do you use?
